- name: Setup docker frontend
  block:
    - name: Pull docker image
      docker_image:
        name: "{{docker_hub_username}}/front:latest"
        source: pull

    - name: Run Docker container
      docker_container:
        name: front
        image: "{{docker_hub_username}}/front:latest"
        state: started
        restart_policy: always
        recreate: true
        pull: true
        networks:
          - name: app-network
