version: '3.7'

services:
  database:
      image: excaliduc/sql:1.0
      ports:
        - "5432:5432"
      networks:
        - "app-network"
      volumes:
        - "data:/var/lib/postgresql/data"
      environment:
        - POSTGRES_DB=db
        - POSTGRES_USER=usr
        - POSTGRES_PASSWORD=pwd

  backend:
      image: excaliduc/api:1.0
      ports:
        - "8080:8080"
      networks:
        - "app-network"
      depends_on:
        - "database"
      environment:
        - DB_URL=jdbc:postgresql://database:5432/db
        - DB_USER=usr
        - DB_PASSWORD=pwd

  httpd:
      image: excaliduc/http:1.0
      ports:
        - "80:80"
      networks:
        - "app-network"
      depends_on:
        - "backend"

networks:
    app-network:

volumes:
  - "data"