- name: Setup docker app
  block:
    - name: Pull docker image
      docker_image:
        name: docker_hub_username/api:latest
        source: pull

    - name: Run Docker container
      docker_container:
        name: backend
        image: "{{docker_hub_username}}"/api:latest
        state: started
        restart_policy: always
        env:
          DB_URL: "{{db_url}}"
          DB_USER: "{{db_user}}"
          DB_PASSWORD: "{{db_password}}"
        networks:
          - name: app-network
